### ISSUE TITLE
Question about Table 2: MPJPE of RVQ on HumanML3D

### ISSUE THREAD

**Issue by RalphHan** [IDEA-Research/HumanTOMATO#7]
MPJPE of RVQ on HumanML3D from [MoMask](https://yxmu.foo/pdfs/momask.pdf) is **29.5**, 
<img width="596" alt="image" src="https://github.com/IDEA-Research/HumanTOMATO/assets/37136590/38a9232e-8352-4c7f-9b4c-8460be3997fb">
but the statistic from your paper is **63.1**. 
<img width="1019" alt="image" src="https://github.com/IDEA-Research/HumanTOMATO/assets/37136590/262e4734-abb6-49ac-9105-1a521e0f6a0f">
Maybe RVQ is not that bad? Can you provide more details about table 2 of your paper?

**Comment by LinghaoChan** [comment]
Hi Hongwei @RalphHan ! Thanks for your question! 

I would like to point out that, in the machine learning community, a fair comparison is needed. In our RVQ, the number of codebooks is 2. In other words, it is quantized by RVQ once. Therefore, basically, it should be compared with Momask (V, 1). It also seems that the 63 is not 54.6. I think the difference is minor. The reason might be complex. (1): Different codebase. We extend the metric calculation from [MLD](https://github.com/ChenFengYe/motion-latent-diffusion). (2): Different VQ implementation. (I am not very sure the difference between our TOMATO model and MoMask) 

Besides, the **fair** comparison of RVQ with VQ should be VQ(1024), which has the same parameters in the codebook(s). BTW, I remember the our FID of RVQ is almost equal to that of Momask (V, 1). However, FID is evaluated by the model and the value is really minor (curve jitters a lot in that scale). Therefore, we do not report the FID for VQ compaction for fearing the model bias. 

Finally, I would like to point out that the scaling of quantizer numbers is not necessary in HumanML3D. Recent models already approach the upper bound of model performance, and sometimes it is difficult for us to determine whether this is because the algorithm really works. And the large number of codebook numbers will slows down the algorithm speed significantly. Therefore, we take the number of codebooks as 2. 

I hope this reply will resolve your question.

**Comment by RalphHan** [comment]
Hi Linghao @LinghaoChan . 

Thank you for your quick reply! It does resolve my question. 
It inspires me that Holistic Hierarchical Residual Vector Quantization (H2RVQ) might be a potential improvement by replacing VQ with RVQ in figure (a). 
<img width="1010" alt="image" src="https://github.com/IDEA-Research/HumanTOMATO/assets/37136590/bca77e90-ffec-42bc-9524-8492042e1583">

**Comment by LinghaoChan** [comment]
> Hi Linghao @LinghaoChan .
> 
> Thank you for your quick reply! It does resolve my question. It inspires me that Holistic Hierarchical Residual Vector Quantization (H2RVQ) might be a potential improvement by replacing VQ with RVQ in figure (a). <img alt="image" width="1010" src="https://private-user-images.githubusercontent.com/37136590/293885540-bca77e90-ffec-42bc-9524-8492042e1583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzY1MjEsIm5iZiI6MTcwNDMzNjIyMSwicGF0aCI6Ii8zNzEzNjU5MC8yOTM4ODU1NDAtYmNhNzdlOTAtZmZlYy00MmJjLTk1MjQtODQ5MjA0MmUxNTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyNDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OTAxYmY4YmEzNGVkMjY3ZGEyNDMyNjUyYzYzM2FiOTZlMzRiNjU1ZTJhZDM3MTlmYWVjZmI1ZmE3YzJhMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iy8_q6JE7NBDmZmuVEMJOoUGimeTPfDGO5EME9eBBo8">

Yep, it really works! For more about it, please refer to the appendix. BTW, I promise you will always learn something from each section of the appendix. (^-^)
